name: Tests

on:
  push:
    branches:
      - main
      - feature/export

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install deps
        run: npm install
      - name: Jast run
        run: npm test
